# Generated by Django 5.2.7 on 2025-10-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='tipo_permissao',
            field=models.CharField(choices=[('colaborador', 'Colaborador'), ('lider', 'Lider'), ('rh', 'RH'), ('admin', 'Admin')], max_length=50),
        ),
    ]
