# Generated by Django 5.2.7 on 2025-10-20 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('sala_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_sala', models.CharField(max_length=45)),
                ('capacidade', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Ocupada', 'ocupada'), ('Desocupada', 'desocupada')], max_length=45)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('planta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='planta.planta')),
            ],
        ),
    ]
