# Generated by Django 5.2.7 on 2025-10-20 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sala',
            old_name='planta_id',
            new_name='planta',
        ),
        migrations.AlterField(
            model_name='sala',
            name='status',
            field=models.CharField(choices=[('ocupada', 'Ocupada'), ('desocupada', 'Desocupa')], max_length=45),
        ),
    ]
