# Generated by Django 5.2.7 on 2025-10-19 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadeira',
            fields=[
                ('id_cadeira', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Ocupado', 'ocupado'), ('Livre', 'livre')], default='Livre', max_length=10)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cadeiras', to='planta.planta')),
            ],
        ),
    ]
